# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{calendar}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["yalab"]
  s.date = %q{2010-12-04}
  s.email = %q{rudeboyjet@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "VERSION",
    "lib/calendar.rb",
    "test/calendar_test.rb"
  ]
  s.homepage = %q{http://github.com/yalab/calendar}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Calendar create library}
  s.test_files = [
    "test/calendar_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

